
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academy?userTimezone=true&serverTimezone=UTC&useLegacyData
    username: gabriel
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true